modLoader="javafml"
loaderVersion="[47,)"
license="GNU LGPL v3.0"
logoFile="tagban_logo.png"
displayURL=""
credits="Thanks to all contributors"

[[mods]]
modId="tagban"
version="1.0.0"
displayName="TagBan"
description="A highly configurable mod that disables specific tools and items based on regex patterns. Supports blacklist/whitelist system with visual tooltip feedback. "
authors="ZhaomingLuomu"

[[dependencies.tagban]]
modId="forge"
mandatory=true
versionRange="[47.1.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.tagban]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21.6)"
ordering="NONE"
side="BOTH"

[[dependencies.tagban]]
modId="cloth-config"
mandatory=false
versionRange="[11.1.118,)"
ordering="AFTER"
side="CLIENT"